%%%%%% Index finder %%%%%%
% This code is used for searching the index events that are from a specific cluster. 
% The cluster is generated by picking clusters manully using the OADC code.

% Input file: target cluster
cluster_file = '/Users/yixinzhang/Desktop/test_HYPODD/Data_2000_2019/SVD/clusFile/cluster1.txt';
cluster_ind_file = 'xyz_ind.reloc';
% Input file: original data file with index
origin_file = '../hypoDD.reloc';

% Output file: Index numbers
% 'index_cluster1.txt'
% phase files
ori_phase_file = '../data_all.phase';
phase_file = 'cluster1.phase';
% cc files
ori_cc_file = '../dt_all.cc';
cc_file = 'cluster1.cc';

% Default parameters (from preFileClusterPick.m) 
x0 = -90;
y0 = 36.35;
d2l = cos(y0/180)*111.699;

% Get event information
event = load(cluster_file);
ind_event = load(cluster_ind_file); 
% ori_event = load(origin_file);

elon = event(:,1);%./d2l + x0;
elat = event(:,2);%./d2l + y0;
edepth = event(:,3);%-event(:,3);
ind = zeros(length(elon),1);

for i = 1:length(elon)
    a = find(ind_event == elon(i)) ;
    b = find(ind_event == elat(i)) - length(ind_event);
    c = find(ind_event == edepth(i)) - 2*length(ind_event);
    ind(i) = intersect(a,intersect(b,c)); % this is the index in origin_file 
end


fid = fopen(ori_phase_file);
fd = fopen(phase_file,'w');
q = 0;

tline = fgetl(fid);
while ischar(tline)
    q = q+1
    while tline(1) == '#'
        n = length(tline)
        temp_ind = find(tline == ' ', 2, 'last')
%         p=p+1;
        id = str2num(tline(temp_ind(1) + 1 : temp_ind(2) - 1))
%         clear temp_ind
        if ismember(id, ind) == 1
            fprintf(fd, [tline '\n'])
            tline = fgetl(fid)
            while tline(1) ~= '#'
                fprintf(fd, [tline '\n'])
                tline = fgetl(fid)
%                 if tline(1)=='#'
%                     break
%                 end
            end
        else
            break
        end
    end
%     tline = fgetl(fid);
end


%     fprintf(fid,'%6.3f %6.3f %5.2f %d \n ', ind_event(ind(i),1), ...
%         ind_event(ind(i),2), ind_event(ind(i),3), ind_event(ind(i),4));
% end

% fclose(fid);
% fclose(fd);
% 
% 
% fid = fopen(ori_cc_file);
% fd = fopen(cc_file,'w');
% p = 0;
% 
% tline = fgetl(fid);
% while ischar(tline)
%     p = p+1;
%     while tline(1) == '#'
%         n = length(tline);
%         temp_ind = find(tline == ' ', 2);
%         id = str2num(tline(temp_ind(1) + 1 : temp_ind(2) - 1));
%         clear temp_ind;
%         if ismember(id, ind) == 1
%             fprintf(fd, [tline '\n']);
%             tline = fgetl(fid);
%             if tline(1) ~= '#'
%                 fprintf(fd, [tline '\n']);
%             elseif tline(1)=='#'
%                 break
%             end
%         else
%             break
%         end
%     end
%     tline = fgetl(fid);
% end
%         
%                 
% 
%             
%             %             while tline(1) ~= '#'
% %                 fprintf(fd, [tline '\n']);
% %                 tline = fgetl(fid);
% %             end
% %         end
% %     end
% %     tline = fgetl(fid);
% % end
% 
% fclose(fid);
% fclose(fd);
%     
% 


